function getEasyStories(){
    let easyStories = [
    {
        "title": "The Last Stop's Secret",
        "summary": "A commuter on a late-night Mumbai train witnesses a suspicious exchange. His discreet attempt to capture evidence pulls him into a dangerous conspiracy, where every shadow hides a threat. He realizes trust is a luxury he can't afford, and his life hangs in the balance.",
        "hints": ["train", "compartment", "bag", "phone", "station", "crowd", "silence", "message", "chase", "city", "escape"],
        "userSelection": [],
        "story": "The Mumbai local train rattled through the humid night. Rohan, a tired commuter, noticed two men across the aisle exchanging a small, unmarked bag. Their furtive glances caught his attention. One man's phone buzzed with a cryptic message. Rohan discreetly snapped a photo. As the train stopped, the men bolted into the crowd. Rohan felt a cold unease. He reviewed the photo: a blurred face, a sinister symbol. His phone vibrated – an unknown number. A distorted voice whispered, 'You saw too much.' The chase had begun. The city became his hunting ground, as he desperately sought truth and escape."
    },
    {
        "title": "Backwater's Silent Current",
        "summary": "A serene houseboat journey in Kerala turns sinister when a passenger vanishes. A sudden storm isolates them. The remaining travelers realize a cunning predator lurks among them, holding a dark secret. Their idyllic trip becomes a desperate fight for survival.",
        "hints": ["houseboat", "backwaters", "passenger", "storm", "silence", "cabin", "map", "whispers", "fear", "night", "water"],
        "userSelection": [],
        "story": "The wooden houseboat glided silently through Kerala's emerald backwaters. Anya noticed a quiet passenger, Vikram, sketching by the railing. Dusk painted the sky, and a violent storm brewed, isolating them on the vast water. During dinner, Vikram was gone. His cabin was empty, save for a cryptic map. An oppressive silence descended, broken by lashing rain. Anya found a hidden compartment on the map, revealing an ancient symbol. A cold whisper rose from the dark current, calling her name. Primal fear gripped them. They realized one of them was not who they seemed, and the backwaters held a darker secret. Their escape depended on uncovering the truth before the water claimed another victim."
    },
    {
        "title": "The Highway's Shifting Sands",
        "summary": "A lone driver on a desolate Rajasthani highway experiences bizarre, terrifying events. Heat and isolation blur reality with illusion. He must decipher the truth behind unsettling mirages and encounters before the desert's secrets claim him, trapping him in an eternal loop.",
        "hints": ["highway", "desert", "car", "heat", "silence", "mirage", "figure", "dust", "whispers", "road", "hallucination", "escape"],
        "userSelection": [],
        "story": "The asphalt highway shimmered across the Rajasthani desert. Arjun, a lone driver, felt oppressive heat despite his car's AC. A profound silence enveloped him. A strange mirage appeared in the distance – a tower that vanished. Unease settled over him. Further down the road, a figure stood, distorted by the shimmering air, then was gone, leaving swirling dust. Faint whispers seemed to rise from the desert, speaking of ancient secrets. His mind, fatigued, began playing tricks, blurring reality with nightmare. The highway twisted impossibly. He gripped the wheel, desperate to find an exit, to escape the desert's embrace and uncover the truth before it consumed him."
    },
    {
        "title": "The Kolkata Files: Metro of Shadows",
        "summary": "A detective, haunted by a cold case, gets an anonymous tip leading him into Kolkata's old metro. He uncovers a hidden conspiracy stretching decades. Every step brings him closer to a dangerous truth, forcing him to confront a present threat in the underground shadows.",
        "hints": ["metro", "tunnels", "detective", "tip", "shadows", "platform", "train", "whispers", "conspiracy", "light", "escape"],
        "userSelection": [],
        "story": "The humid air of Kolkata hung heavy as Detective Sharma descended into the old metro. An anonymous tip promised answers to a cold case. Dimly lit tunnels stretched into oppressive darkness, trains echoing like a heartbeat. He walked a deserted platform, his flashlight cutting gloom, revealing forgotten graffiti. A faint whisper brushed his ear, a fragment from the past. He dismissed it, but dread built. Deeper, he found a hidden door to disused passages. The air grew thick with damp earth and old secrets. He realized he was unraveling a sinister conspiracy, embedded in the city's underbelly. Every flickering light brought him closer to a dangerous truth. The metro became a labyrinth, and his escape depended on outsmarting unseen forces."
    },
    {
        "title": "The Ooty Express: Final Destination",
        "summary": "On the Ooty Mountain Railway, passengers are isolated when the train halts in a remote, misty section. A thick fog descends, and unsettling events unfold, revealing a hidden agenda. They realize a fellow traveler harbors a dark secret, turning the scenic journey into a deadly trap with no escape.",
        "hints": ["train", "hills", "passengers", "fog", "tracks", "silence", "compartment", "whispers", "secret", "trap", "escape"],
        "userSelection": [],
        "story": "The Ooty Mountain Railway chugged through the Nilgiri Hills. Passengers admired views. Suddenly, the train halted in a remote, misty section, far from any station. Thick fog descended, swallowing the landscape. An unsettling silence fell over the compartment. The driver was gone. Faint whispers circulated, hushed theories, but a deeper unease settled in. One passenger clutched a briefcase. Strange occurrences began: flickering light, a misplaced bag, a chilling note. They realized this was no breakdown; it was a trap. One harbored a dark secret, and the scenic journey had become a final destination with no escape, as the fog concealed their plight."
    },
    {
        "title": "The Red Fort's Cryptic Code",
        "summary": "A cryptographer uncovers a hidden message in Delhi's Red Fort. His pursuit leads him into a dangerous labyrinth of conspiracies and modern threats. He must decipher the message before a shadowy organization silences him permanently.",
        "hints": ["fort", "cryptographer", "message", "architecture", "walls", "chambers", "symbol", "map", "conspiracy", "secret", "Delhi"],
        "userSelection": [],
        "story": "The Red Fort stood majestic, its ancient walls holding history. Dr. Anya Sharma, a brilliant cryptographer, believed it held a hidden message in its architecture. Her obsession led her to study its patterns. One evening, shadows at an archway revealed a faint symbol – the key. Her pursuit led her deep into forgotten chambers, where she found a fragmented map hinting at a vault. Her discovery hadn't gone unnoticed. A shadowy, ruthless organization wanted the fort's secrets buried. They closed in. Anya raced, deciphering the next part, realizing the conspiracy was far grander. Her escape depended on uncovering the truth before they silenced her, making her another forgotten secret of the Red Fort."
    },
    {
        "title": "The Silent Hills of Darjeeling",
        "summary": "A journalist investigates disappearances in Darjeeling's misty hills, uncovering a sinister cult. The mountains become a nightmare as locals hide secrets. She must expose the truth behind the disappearances and rituals before becoming their next victim, with no one to hear her screams.",
        "hints": ["hills", "journalist", "disappearances", "cult", "town", "tea", "mist", "rituals", "silence", "temple", "escape"],
        "userSelection": [],
        "story": "The misty, tea-covered hills of Darjeeling held a chilling secret for journalist Priya. She investigated mysterious disappearances, locals vanishing without a trace. Her inquiries led her to a remote part of the mountains, where unsettling silence hung heavy. She suspected a sinister local cult. As she delved deeper, the idyllic beauty transformed into a claustrophobic nightmare. Every local seemed to hide something. She found an ancient temple, hidden in mist, hearing faint chanting. The air grew cold, thick with incense and something unsettling. She realized disappearances linked to gruesome rituals. Priya knew she had to expose the truth before becoming their next victim. Her frantic escape through the silent hills was a desperate race against time, her scream swallowed by the mist."
    },
    {
        "title": "Gateway of Whispers: Mumbai Docks",
        "summary": "A struggling dockworker in Mumbai stumbles upon a hidden smuggling operation. His discovery pulls him into a dangerous underworld of crime and betrayal. He must expose the illicit network and outwit powerful figures who control the port's shadows, before they silence him permanently.",
        "hints": ["docks", "worker", "operation", "cargo", "ship", "night", "whispers", "figure", "underworld", "betrayal", "escape", "city"],
        "userSelection": [],
        "story": "The bustling Mumbai docks, a chaotic symphony, were a world unto themselves. Rahul, a struggling dockworker, was on night shift when he stumbled upon a hidden smuggling operation. A specific crate held illicit cargo. His accidental discovery pulled him into a dangerous underworld of crime and betrayal. He noticed a shadowy figure observing him from a distant ship. The night air carried hushed whispers of illicit deals. He found a cryptic message in the manifest, hinting at powerful figures controlling the port. Rahul realized he was a pawn in a larger, deadlier game. He had to expose the network, but every move tightened the noose. His escape depended on outwitting ruthless enemies who hunted him through the docks, before they silenced him, making him another forgotten secret of the port city."
    },
    {
        "title": "The Ghost of Charminar's Bazaar",
        "summary": "In Hyderabad's Charminar bazaar, an antique dealer uncovers a cursed artifact. Its acquisition unleashes a malevolent spirit, blurring reality and nightmare. He must break the curse and return the artifact before he loses his mind or becomes another victim claimed by the ancient entity.",
        "hints": ["bazaar", "dealer", "artifact", "spirit", "lanes", "charminar", "market", "whispers", "curse", "shadows", "escape"],
        "userSelection": [],
        "story": "The vibrant bazaar surrounding Hyderabad's Charminar pulsed with life. Rohan, a young antique dealer, stumbled upon a peculiar, carved wooden box in a dusty shop. He felt an inexplicable pull. Back in his shop, a faint whisper emanated from it. He dismissed it, but dread settled. The next night, objects moved, shadows danced, and whispers grew louder. He realized the artifact was cursed, tied to a malevolent spirit haunting his shop and extending its influence into the city's lanes. Reality blurred. Rohan knew he had to break the curse and return the artifact before he lost his mind or became another victim. His escape depended on uncovering its dark history."
    },
    {
        "title": "The Vanishing Point of Yamuna Expressway",
        "summary": "On the Yamuna Expressway, a tech entrepreneur experiences terrifying glitches. His GPS malfunctions, the road twists, and phantom vehicles appear. He realizes he's trapped in a digital nightmare, a simulated reality controlled by an unknown entity. He must break free before he's permanently lost.",
        "hints": ["expressway", "entrepreneur", "GPS", "road", "glitches", "vehicle", "signals", "reality", "loop", "entity", "escape"],
        "userSelection": [],
        "story": "The sleek Yamuna Expressway stretched into the inky night. Arjun, a tech entrepreneur, was driving alone when his GPS malfunctioned, displaying impossible routes. He dismissed it, but the road itself twisted ahead, lane markers shifting. Phantom vehicles appeared and vanished in his mirror. Disorientation settled. His phone lost all signals. He tried to turn back, but exits vanished. A chilling realization dawned: he was trapped in a digital nightmare, a simulated reality controlled by an unknown entity. The same road repeated, an endless loop. He saw a faint, distorted figure in his passenger seat. His mind raced, desperate to break free from the system before he became permanently lost, his consciousness absorbed into the void."
    },
    {
        "title": "The Haunting of Victoria Memorial",
        "summary": "A lonely archivist working late at Kolkata's Victoria Memorial discovers a hidden chamber with forbidden records. His research turns into a chilling encounter with restless colonial spirits, revealing a dark secret about the monument. He must uncover the truth and appease the tormented souls before he becomes another permanent fixture in its haunted history.",
        "hints": ["memorial", "archivist", "chamber", "records", "history", "spirits", "dome", "whispers", "figure", "truth", "escape"],
        "userSelection": [],
        "story": "The majestic Victoria Memorial stood silent under the Kolkata night. Rohan, a lonely archivist, worked late in its vast, echoing halls. He stumbled upon a hidden chamber, concealed behind a bookshelf, containing forbidden records hinting at a darker past. His research turned chilling. Faint whispers, in archaic English, drifted from shadows. He dismissed them, but a spectral figure, clad in colonial attire, appeared, its eyes burning with ancient sorrow. The air grew heavy with dust and forgotten tragedies. He realized restless colonial spirits were alive within the Memorial. They resented his intrusion, their whispers menacing. Rohan knew he had to uncover the full truth and appease the tormented souls before he became another permanent fixture in its haunted history. His only escape was to solve the mystery before the night consumed him."
    }
]
return easyStories;
}

function getMediumStories(){
    let mediumStories = [
            {
        "title": "The Last Stop's Secret",
        "summary": "A weary commuter on a late-night Mumbai local train inadvertently witnesses a suspicious, covert exchange between two enigmatic men. His attempt to discreetly capture evidence of this mysterious transaction plunges him into a dangerous and escalating conspiracy, where every fleeting shadow seems to conceal a new threat. He quickly realizes that in this treacherous new reality, trust is a perilous luxury he can no longer afford, and his life hangs in the balance.",
        "hints": ["train", "compartment", "eyes", "bag", "phone", "station", "crowd", "silence", "message", "chase", "city", "truth", "escape"],
        "userSelection": [],
        "story": "The Mumbai local train rattled, a metal beast slicing relentlessly through the humid, suffocating night, its rhythmic clatter a deceptive lullaby. Rohan, a tired commuter, slumped heavily in the crowded compartment, his gaze drifting aimlessly across the weary faces. Across the aisle, two men exchanged a small, unmarked bag. Their furtive glances and the palpable tension in their eyes instantly caught his attention, a silent alarm bell ringing in his mind. One man's phone buzzed, displaying a cryptic, unsettling message that flashed briefly. Rohan instinctively pulled out his own phone, snapping a quick, discreet photo. As the train screeched to a sudden halt at the next bustling station, the two men abruptly bolted, disappearing with alarming speed into the surging, indifferent crowd. Rohan felt a prickle of profound unease, a cold silence settling around him despite the surrounding noise. He reviewed the photo: a blurred face, a fleeting glimpse of a sinister symbol. His phone vibrated – an unknown number. A distorted, chilling voice whispered, 'You saw too much. Now, you’re part of it.' The relentless chase had begun. The vast, indifferent city became his hunting ground, or perhaps, his inescapable tomb, as he desperately sought the truth and a desperate way to escape."
    },
    {
        "title": "Backwater's Silent Current",
        "summary": "A seemingly serene houseboat journey through the tranquil, emerald backwaters of Kerala takes a sinister and chilling turn when a fellow passenger mysteriously vanishes without a trace. As a sudden, violent storm brews and isolates them further, the remaining travelers realize with growing dread that they are trapped, isolated, and that a cunning predator lurks silently among them, hiding a dark, deadly secret beneath the calm surface of the water. Their idyllic trip transforms into a desperate fight for survival.",
        "hints": ["houseboat", "backwaters", "passenger", "storm", "silence", "cabin", "map", "whispers", "current", "fear", "night", "escape", "water"],
        "userSelection": [],
        "story": "The polished wooden houseboat glided silently through Kerala's emerald backwaters, a picture of serene, almost deceptive beauty under the fading sun. Anya, enjoying the tranquil journey, noticed a fellow passenger, a quiet man named Vikram, sketching intently by the railing, his face obscured. As dusk painted the sky in bruised purples, a sudden, violent storm brewed, trapping them on the isolated, vast water, cutting off all contact with the shore. During a tense dinner, Vikram was inexplicably gone. His cabin was utterly empty, save for a half-drawn, cryptic map left carelessly on his bed. An unnerving, oppressive silence descended upon the remaining passengers, broken only by the lashing rain against the windows and the ominous creak of the boat's timbers. Anya found a hidden compartment on Vikram's map, revealing a chilling, ancient symbol. A cold, guttural whisper seemed to rise from the dark current beneath the boat, calling her name. Primal fear gripped them all. As the night deepened, they realized with horrifying certainty that one of them was not who they seemed, and the backwaters held a secret far darker and more dangerous than its depths. Their very escape depended on uncovering the truth before the treacherous water claimed another victim."
    },
    {
        "title": "The Highway's Shifting Sands",
        "summary": "On a desolate, endless highway stretching across the vast, sun-baked Rajasthani desert, a lone driver embarks on a journey that quickly devolves into a series of bizarre and increasingly terrifying events. As the scorching heat and isolation cause reality to blur with sinister illusion, he must desperately decipher the chilling truth behind the unsettling mirages and strange encounters before the desert's ancient, malevolent secrets claim him forever, trapping him in an eternal, horrifying loop.",
        "hints": ["highway", "desert", "car", "heat", "silence", "mirage", "figure", "dust", "whispers", "road", "hallucination", "truth", "escape", "journey"],
        "userSelection": [],
        "story": "The asphalt highway shimmered, a black ribbon stretching endlessly across the vast, sun-baked Rajasthani desert, seemingly leading nowhere. Arjun, a lone driver on a long, arduous journey, felt the oppressive, suffocating heat radiating even through his car's fully functioning air-conditioning. A profound, unsettling silence enveloped him, broken only by the monotonous hum of his engine and the occasional distant crow. Then, a strange, shimmering mirage appeared in the distance – a towering, ancient structure that vanished abruptly as he approached, leaving only the empty horizon. A prickle of profound unease, a sense of being watched, settled over him. Further down the desolate road, a lone, indistinct figure stood by the roadside, its form distorted by the shimmering air, waving faintly. He blinked, and it was gone, leaving only swirling dust devils in its wake. Faint, insidious whispers seemed to rise from the desert itself, carried on the hot, dry wind, speaking of ancient, forgotten secrets and impending doom. His mind, fatigued by the endless journey and the oppressive solitude, began to play terrifying tricks, blurring reality with vivid, nightmarish hallucination. The highway twisted impossibly, the very landscape shifting around him. He gripped the steering wheel, knuckles white, desperate to find an exit, to escape the desert's sinister, inescapable embrace and uncover the terrifying truth before it consumed him entirely."
    },
    {
        "title": "The Kolkata Files: Metro of Shadows",
        "summary": "A seasoned detective, haunted by a cold case, receives an anonymous tip leading him into the labyrinthine depths of Kolkata's old metro system. As he descends into the dimly lit tunnels, he uncovers a hidden network of secrets and a sinister conspiracy that stretches back decades. Every echoing footstep and flickering light brings him closer to a truth far more dangerous than he imagined, forcing him to confront not just the past, but a present threat lurking in the shadows of the underground.",
        "hints": ["metro", "tunnels", "detective", "tip", "shadows", "platform", "train", "whispers", "past", "conspiracy", "light", "escape", "truth", "city"],
        "userSelection": [],
        "story": "The humid air of Kolkata hung heavy, but a deeper chill settled over Detective Sharma as he descended into the old metro system. An anonymous tip, scrawled on a crumpled paper, promised answers to a cold case that had haunted him for years. The dimly lit tunnels stretched into an oppressive darkness, the rhythmic hum of distant trains echoing like a heartbeat. He walked along a deserted platform, his flashlight beam cutting through the gloom, revealing forgotten graffiti and a pervasive sense of unease. A faint whisper seemed to brush his ear, a fragment of a conversation from the past. He dismissed it, but a cold dread began to build. As he ventured deeper, he found a hidden door, leading to a network of disused passages. The air grew thick, heavy with the scent of damp earth and old secrets. He realized he was not just chasing a criminal; he was unraveling a sinister conspiracy that stretched back decades, deeply embedded in the city's underbelly. Every flickering light and echoing footstep brought him closer to a truth that was far more dangerous than he could have imagined. The metro, once a symbol of progress, became a labyrinth of shadows, and his escape depended on outsmarting the unseen forces that now hunted him."
    },
    {
        "title": "The Ooty Express: Final Destination",
        "summary": "On a picturesque journey through the Nilgiri Hills aboard the historic Ooty Mountain Railway, a group of diverse passengers finds themselves unexpectedly isolated when the train inexplicably grinds to a halt in a remote, misty section of the tracks. As a thick fog descends, cutting them off from the outside world, a series of unsettling events begins to unfold, revealing a hidden agenda among them. They soon realize that one of their fellow travelers harbors a dark secret, and the scenic journey has become a deadly trap with no obvious escape.",
        "hints": ["train", "hills", "passengers", "fog", "tracks", "silence", "compartment", "whispers", "secret", "driver", "station", "trap", "escape", "destination"],
        "userSelection": [],
        "story": "The historic Ooty Mountain Railway chugged leisurely through the picturesque Nilgiri Hills, a charming relic of a bygone era. A diverse group of passengers, from honeymooners to lone adventurers, admired the breathtaking views. Suddenly, with a jarring lurch, the train inexplicably ground to a halt in a remote, misty section of the tracks, far from any station. A thick, impenetrable fog descended almost instantly, swallowing the landscape and cutting them off completely. An unsettling silence fell over the compartment, broken only by the nervous coughs of the passengers. The driver was nowhere to be found. Faint whispers began to circulate, hushed theories about the delay, but a deeper unease settled in. One passenger, a stern-faced man, clutched a worn leather briefcase tightly. As the hours passed, strange occurrences began: a flickering light, a misplaced bag, a chilling note slipped under a door. They soon realized with growing dread that this wasn't just a breakdown; it was a carefully orchestrated trap. One of them harbored a dark secret, and the scenic journey had become a final destination from which there seemed to be no escape, as the fog pressed in, concealing their plight from the world."
    },
    {
        "title": "The Red Fort's Cryptic Code",
        "summary": "A brilliant but eccentric cryptographer, obsessed with ancient Indian mysteries, uncovers a hidden message embedded within the intricate architecture of Delhi's iconic Red Fort. His relentless pursuit of this cryptic code leads him into a dangerous labyrinth of historical conspiracies and modern-day threats. As he races against time, he must decipher the true meaning of the message before a shadowy organization, determined to keep the fort's secrets buried forever, silences him permanently.",
        "hints": ["fort", "cryptographer", "message", "architecture", "walls", "chambers", "symbol", "map", "conspiracy", "organization", "truth", "escape", "secret", "Delhi"],
        "userSelection": [],
        "story": "The iconic Red Fort of Delhi stood majestic under the morning sun, its ancient red sandstone walls holding centuries of history. Dr. Anya Sharma, a brilliant but eccentric cryptographer, believed it also held a hidden message, embedded within its intricate architecture. Her obsession led her to spend countless hours studying its patterns. One evening, a peculiar alignment of shadows at a specific archway revealed a faint, almost invisible symbol. This was it: the key to the cryptic code. Her relentless pursuit of this message led her deep into the fort's forgotten chambers, where the air was thick with dust and untold stories. She found a fragmented map, hinting at a hidden vault. But her discovery hadn't gone unnoticed. A shadowy organization, ancient and ruthless, was determined to keep the fort's secrets buried forever. They began to close in, their presence a chilling whisper in the empty halls. Anya raced against time, deciphering the next part of the message, realizing the true meaning behind the conspiracy was far grander and more dangerous than she had imagined. Her escape depended on uncovering the ultimate truth before they silenced her permanently, making her another forgotten secret of the Red Fort."
    },
    {
        "title": "The Silent Hills of Darjeeling",
        "summary": "A young journalist, investigating a series of mysterious disappearances in the misty, tea-covered hills of Darjeeling, finds herself entangled in a sinister local cult. As she delves deeper into the town's dark secrets, the idyllic beauty of the mountains transforms into a claustrophobic nightmare, where every local seems to be hiding something. She must expose the chilling truth behind the disappearances and the cult's rituals before she becomes their next victim, with no one to hear her screams in the silent hills.",
        "hints": ["hills", "journalist", "disappearances", "cult", "town", "tea", "mist", "rituals", "silence", "temple", "truth", "escape", "mountains", "scream"],
        "userSelection": [],
        "story": "The misty, tea-covered hills of Darjeeling usually exuded a serene charm, but for young journalist Priya, they now held a chilling secret. She was investigating a series of mysterious disappearances, locals vanishing without a trace. Her inquiries led her to a remote, secluded part of the mountains, where an unsettling silence hung heavy in the air, broken only by the rustling of tea leaves. She suspected a sinister local cult was involved, their presence a palpable dread. As she delved deeper into the town's dark secrets, the idyllic beauty transformed into a claustrophobic nightmare. Every local she questioned seemed to be hiding something, their eyes evasive, their smiles thin. She found an ancient, overgrown temple, hidden deep within a thick patch of mist, where she heard faint, rhythmic chanting. The air grew cold, thick with the scent of incense and something else, something metallic and unsettling. She realized the disappearances were linked to gruesome rituals. Priya knew she had to expose the chilling truth before she became their next victim. Her frantic escape through the silent hills was a desperate race against time, her unheard scream swallowed by the pervasive mist."
    },
    {
        "title": "Gateway of Whispers: Mumbai Docks",
        "summary": "A struggling dockworker in Mumbai stumbles upon a hidden smuggling operation on the bustling, chaotic docks. His accidental discovery pulls him into a dangerous underworld of crime and betrayal, forcing him to navigate treacherous alliances and ruthless enemies. As he tries to expose the illicit network, he realizes he's a pawn in a much larger game, and his only hope for survival is to outwit the powerful figures who control the shadows of the port city, before they silence him permanently.",
        "hints": ["docks", "worker", "operation", "cargo", "ship", "night", "whispers", "figure", "underworld", "betrayal", "escape", "port", "city", "truth"],
        "userSelection": [],
        "story": "The bustling Mumbai docks, a chaotic symphony of creaking cranes and shouting voices, were a world unto themselves. Rahul, a struggling dockworker, was enduring another grueling night shift when he stumbled upon a hidden smuggling operation. A specific crate, marked innocently, held illicit cargo far more valuable than it appeared. His accidental discovery pulled him into a dangerous underworld of crime and betrayal. As he tried to gather more evidence, he noticed a shadowy figure observing him from a distant ship. The night air, thick with the scent of salt and diesel, seemed to carry hushed whispers of illicit deals. He found a cryptic message hidden within the cargo manifest, hinting at powerful figures controlling the entire port. Rahul realized he was a pawn in a much larger, deadlier game. He had to expose the network, but every move he made seemed to tighten the noose around him. His escape depended on outwitting the ruthless enemies who now hunted him through the labyrinthine docks, before they silenced him permanently, making him another forgotten secret of the port city."
    },
    {
        "title": "The Ghost of Charminar's Bazaar",
        "summary": "In the vibrant, bustling lanes surrounding Hyderabad's iconic Charminar, a young antique dealer uncovers a cursed artifact with a dark history. His acquisition unleashes a malevolent spirit, tied to the artifact and the very fabric of the old city's bazaar. As the spirit's influence grows, blurring the lines between reality and nightmare, he must find a way to break the curse and return the artifact before he loses his mind or becomes another victim claimed by the ancient entity that haunts the labyrinthine alleys.",
        "hints": ["bazaar", "dealer", "artifact", "spirit", "lanes", "charminar", "market", "whispers", "curse", "shadows", "truth", "escape", "city", "mind"],
        "userSelection": [],
        "story": "The vibrant, chaotic bazaar surrounding Hyderabad's iconic Charminar pulsed with life, a symphony of haggling and aromas. Rohan, a young antique dealer with a keen eye for the unusual, stumbled upon a peculiar, intricately carved wooden box in a dusty corner shop. He felt an inexplicable pull towards it. Back in his small shop, as he cleaned the artifact, a faint, chilling whisper seemed to emanate from it. He dismissed it, but a cold dread began to settle in. The next night, strange things happened: objects moved, shadows danced in his peripheral vision, and the whispers grew louder, more insistent, speaking an ancient language. He realized the artifact was cursed, tied to a malevolent spirit that now haunted his shop and slowly began to extend its influence into the labyrinthine lanes of the old city. The lines between reality and nightmare began to blur. Rohan knew he had to find a way to break the curse and return the artifact before he lost his mind or became another victim claimed by the ancient entity that now stalked him. His escape from its grasp depended on uncovering the truth of the artifact's dark history."
    },
    {
        "title": "The Vanishing Point of Yamuna Expressway",
        "summary": "On the modern, high-speed Yamuna Expressway, a tech entrepreneur driving alone late at night experiences a series of disorienting and terrifying glitches. His GPS malfunctions, the road seems to twist impossibly, and phantom vehicles appear and vanish. He soon realizes he's trapped in a digital nightmare, a simulated reality controlled by an unknown entity, and his only hope for survival is to find a way to break free from the loop before he becomes permanently lost in the system.",
        "hints": ["expressway", "entrepreneur", "GPS", "road", "glitches", "vehicle", "signals", "reality", "loop", "entity", "escape", "system", "mind", "night"],
        "userSelection": [],
        "story": "The sleek, modern Yamuna Expressway stretched endlessly into the inky night, a ribbon of concrete cutting through the darkness. Arjun, a tech entrepreneur, was driving alone, pushing his car to its limits, when his GPS suddenly malfunctioned, displaying impossible routes. He dismissed it as a minor glitch, but then the road itself seemed to twist impossibly ahead, the lane markers shifting like liquid. Phantom vehicles appeared and vanished in his rearview mirror, their headlights flickering erratically. A profound sense of disorientation settled over him. His phone lost all signals, plunging him into complete isolation. He tried to turn back, but the exit ramps seemed to have vanished. A chilling realization dawned: he was trapped in a digital nightmare, a simulated reality controlled by an unknown entity. The same stretch of road repeated, an endless loop. He saw a faint, distorted figure in his passenger seat, its form flickering like a bad connection. His mind raced, desperate to find a way to break free from the system before he became permanently lost, his consciousness absorbed into the digital void of the Yamuna Expressway."
    },
    {
        "title": "The Haunting of Victoria Memorial",
        "summary": "Under the grand dome of Kolkata's Victoria Memorial, a lonely archivist working late discovers a hidden chamber containing forbidden historical records. His quiet research turns into a chilling encounter with the restless spirits of the colonial past, revealing a dark secret about the monument itself. As the spectral presences grow more aggressive, he must uncover the full truth and find a way to appease the tormented souls before he becomes another permanent fixture in the Memorial's haunted history.",
        "hints": ["memorial", "archivist", "chamber", "records", "history", "spirits", "dome", "whispers", "figure", "past", "truth", "escape", "monument", "night"],
        "userSelection": [],
        "story": "The majestic Victoria Memorial stood silent under the Kolkata night sky, its grand dome a beacon of colonial history. Rohan, a lonely archivist, was working late in its vast, echoing halls, meticulously cataloging old documents. He stumbled upon a hidden chamber, concealed behind a false bookshelf, containing forbidden historical records that hinted at a darker past. His quiet research quickly turned into a chilling encounter. Faint whispers, speaking in archaic English, drifted from the shadows. He dismissed them as fatigue, but then a spectral figure, clad in old colonial attire, appeared at the end of the long corridor, its eyes burning with an ancient sorrow. The air grew heavy, thick with the scent of dust and forgotten tragedies. He realized the restless spirits of the colonial past were very much alive within the Memorial. They seemed to resent his intrusion, their whispers growing into menacing murmurs. Rohan knew he had to uncover the full truth of the monument's dark secret and find a way to appease the tormented souls before he became another permanent fixture in its haunted history. His only escape was to solve the mystery before the night consumed him."
    }
    ]
    return mediumStories;
}


export {getEasyStories ,getMediumStories};