function getEasyStories(){
    let easyStories = [
    {
        title: "The Silent Ward",

        summary: " a night guard working in an abandoned hospital. His routine check of a desolate isolation wing takes a terrifying turn when strange noises lead him to Room 7. Inside, he discovers unsettling markings on the walls and a single, chilling object, hinting at the unsettling past of the place and the lingering presence of its former inhabitants.",

        hints: ['wing', 'broken', 'spine', 'room u7', 'bare', 'Scratches', 'Porcelain eye', 'wishper'],

        userSelection: [],
        story: "The chill in the old hospital's abandoned wing wasn't just from the wishper windows. Liam, the new night guard, felt a prickle down his room u7 as he checked the locked doors of the isolation ward. A faint, rhythmic scratching echoed from Scratches. He hesitated, flashlight beam trembling, before pushing the heavy door open The room was Porcelain eye, save for a single, rusted bed.On the dust- covered wall, hundreds of tiny, parallel broken marred the paint, forming an unsettling pattern.It wasn't just one set; they overlapped, intertwining. As his light swept across the floor, he saw a single, antique doll, its spine staring blankly at the wall. Then, from the darkness behind him, a bare, \"We're still here...",
    },
    {
        title: "The Whispering Woods",

        summary: "\"The Whispering Woods\" plunges players into a camping trip gone wrong. Ignoring local warnings, three friends venture into a foreboding forest. As night falls, unsettling noises and mysterious presences emerge from the darkness, revealing the woods' ancient and terrifying secrets.",

        hints: ['dancing', 'blackwood Forest', 'whispers', 'chill', 'tapping', 'trees', 'child\'s', 'giggle', 'darkness'],
        userSelection: [],
        story: "The campfire crackled, casting dancing shadows among the towering pines. Sarah, Mark, and Emily had ignored the old local's warnings about the Blackwood Forest. Deep in the woods, an unnerving silence fell, broken only by the rustling of leaves and what sounded like faint whispers carried on the wind. Later, huddled in their tents, a chill seeped into their sleeping bags. A rhythmic tapping began, not on their tent, but from within the surrounding trees. It grew louder, accompanied by what sounded like a child's giggle – distorted and far too close. Mark peered through the mesh, seeing nothing but the impenetrable darkness. Then, a single, glowing eye opened in the black, staring back. They didn't scream; they simply froze, listening to the forest breathing."

    },
    {
        title: "The Lady in White's Ride",

        summary: "\"The Lady in White's Ride\" follows Aryan, who encounters a mysterious woman in a white saree while driving on a foggy Delhi road late at night. She suddenly appears in his back seat, filling the car with the scent of flowers. As the temperature drops, a ghostly voice requests a ride to the cemetery, leaving Aryan with a chilling reminder of his spectral passenger.",

        hints: ['headlights', 'home', 'chill', 'mist', 'woman', 'saree', 'flowers', 'ear', 'cemetery'],
        userSelection: [],
        story: "The headlights cut through the dense fog on the Delhi Cantt road. Aryan, driving home late, felt an inexplicable chill despite the warm night. Ahead, a solitary figure emerged from the swirling mist: a woman in a white saree, her back to him. He slowed, wary. As he passed, she was suddenly inside his back seat. Her hair, long and black, obscured her face. A faint scent of old flowers filled the car. Aryan's hands gripped the steering wheel, knuckles white. The temperature inside plummeted. A cold breath ghosted across his ear. \"Drop me at the cemetery,\" a raspy voice whispered. He slammed the brakes, heart hammering, and looked back. The seat was empty, but the faint scent of jasmine lingered, a chilling reminder of his spectral passenger."
    },
    {
    "title": "The Whispering Mansion",
    "summary": "A group of daring explorers, fueled by curiosity, decides to venture into a notoriously haunted mansion, defying long-standing local legends of its cursed grounds. As they navigate the crumbling structure, they begin to encounter a series of chilling supernatural phenomena, from disembodied whispers to unseen touches, gradually realizing they are not alone within the mansion's ancient, eerie walls. Their brave exploration quickly turns into a terrifying fight for survival against the dwelling's spectral inhabitants.",
    "hints": ["gates", "house", "legends", "giggle", "hand", "mansion", "fragrance", "voices", "explorers", "flashlight"],
    "userSelection": [],
    "story": "The crumbling mansion stood silhouetted against the stormy sky. Local legends warned against its cursed grounds. A group of young explorers, daring and foolish, crept past the rusty gates. Inside, dust motes danced in the lone beam of a flashlight. A strange, sweet fragrance hung heavy in the air, like forgotten flowers. Suddenly, a cold breeze swept through the empty halls, extinguishing their light. A child's faint giggle echoed from the darkness. One of them, a girl named Maya, felt a tiny hand brush her leg. Her heart pounded against her ribs. The whispers began, a chorus of tiny voices from the shadows. They fumbled for their phones, but the screens remained stubbornly black. They were not alone in this house."
},
    {
    "title": "Bhangarh's Shadow",
    "summary": "Legend strictly warns against staying within Bhangarh Fort after sunset, due to an ancient curse. A curious tourist, defying these ominous warnings, decides to challenge fate by remaining in the desolate ruins through the night. He soon discovers the chilling reality of the fort's spectral inhabitants, facing terrifying spirits that actively roam its haunted grounds, making his defiance a perilous encounter.",
    "hints": ["whisper", "figure", "sunset", "curse", "breeze", "tourist", "fort", "eyes", "melody", "ruins"],
    "userSelection": [],
    "story": "The ancient fort of Bhangarh stood silent as dusk painted the sky. Rahul, a lone tourist, scoffed at the legends warning against staying after sunset. He climbed to the highest tower, eager to witness the forbidden night. A cold breeze swept through the empty chambers, carrying a faint, mournful melody. He dismissed it as the wind. Suddenly, a shadowy figure appeared in the archway below, its hollow eyes fixed on him. No sound escaped its lips, but a chilling whisper echoed in his mind: 'You've crossed the boundary.' Panic surged. He scrambled down the crumbling walls, the fort's vengeful spirits pursuing him through the desolate ruins. Bhangarh had claimed another."
    },
    {
    "title": "Dumas Beach's Embrace",
    "summary": "A group of friends, seeking an adrenaline rush, decides to visit the notorious black sands of Dumas Beach. Despite unsettling local legends, they venture onto the desolate shore. As night deepens, they begin to hear chilling whispers carried on the wind, subtly drawing them deeper into the beach's dark secrets. They soon face a terrifying and seemingly inescapable fate as the supernatural presence reveals its true power, making their thrill-seeking adventure a night of pure horror.",
    "hints": ["wind", "waves", "sands", "shore", "laughter", "darkness", "beach", "whispers", "footprints", "embrace"],
    "userSelection": [],
    "story": "The black sand of Dumas Beach stretched endlessly under the moonless sky. Four friends, seeking thrill, disregarded the local warnings. They walked along the desolate shore, the rhythmic crash of waves strangely muted. Soon, faint whispers reached their ears, carried on the chilling wind. It sounded like a chorus of distant laughter, eerie and inviting. As they ventured further, the whispers grew clearer, seeming to call their names. A cold dread settled over them. They looked back; their footprints in the sand were vanishing, not by the waves, but as if dragged under. The darkness seemed to press in, thick and suffocating. A chilling force pulled at their ankles, a silent, unseen embrace. On the shore, only the whispers remained."
    },
    {
    "title": "Mukesh Mills' Silent Echoes",
    "summary": "A daring documentary crew, seeking to expose supernatural truths, ventures into Mumbai's infamous and abandoned Mukesh Mills. Known for its chilling history and eerie atmosphere, the crew soon finds themselves inexplicably trapped within the crumbling complex, facing the terrifying reality of its unseen, lingering residents. Their investigative journey quickly transforms into a desperate struggle for survival against the mill's ghostly inhabitants.",
    "hints": ["figure", "camera", "factory", "whispers", "gates", "silence", "shadow", "exit", "crew", "mills"],
    "userSelection": [],
    "story": "The desolate mills stood stark against the Mumbai skyline, a monument to forgotten industry. A documentary crew, bold and ambitious, entered its crumbling gates, their camera ready to capture the eerie atmosphere. Inside, an unnatural silence enveloped them, broken only by the crunch of debris underfoot. Then, a fleeting shadow darted across a distant window in the derelict factory. The air grew heavy, thick with the scent of damp concrete and unseen dread. Faint whispers began, like a forgotten conversation from the past. A tall, spectral figure appeared at the end of a corridor, its form shimmering in the dim light. Panic set in. They raced for the exit, but the massive doors slammed shut, locking them inside with the ghosts of Mukesh Mills."
    },
    {
    "title": "The Peshwa's Cry",
    "summary": "At the historic Shaniwarwada Fort, a new night watchman's routine shift turns into a terrifying ordeal. He encounters the infamous, desperate cry of a murdered young prince, a chilling sound that seems to draw him deeper into the fort's tragic and violent past, forcing him to confront its spectral and lingering presence.",
    "hints": ["darkness", "walls", "gate", "figure", "fort", "hallway", "echo", "voice", "watchman", "escape"],
    "userSelection": [],
    "story": "The massive iron gate of Shaniwarwada Fort groaned shut, trapping Arjun, the new night watchman, within its ancient walls. He began his rounds, his flashlight beam piercing the gloom. A cold echo seemed to follow him through the deserted courtyards. As he approached the notorious hallway, a faint, desperate cry pierced the silence: 'Kaka mala vachva!' (Uncle, save me!). It was the ghostly voice of a murdered young prince. Panic seized him. A shadowy figure darted across the archway, just beyond his sight. He fumbled, dropping his torch, plunging into utter darkness. The chilling voice grew louder, closer. He stumbled backward, desperate for an escape, but the fort's ancient power seemed to hold him fast within its cold, stone walls."
    },
    {
    "title": "The Lament of Three Kings",
    "summary": "Atop a Goan hill, the Three Kings Chapel harbors a dark history of poisoned monarchs. A group of curious students dares to explore its eerie interior after dusk. They soon encounter chilling phenomena: disembodied sounds, spectral figures, and a pervasive sense of dread, realizing the chapel's tragic past still echoes within its ancient walls. Their exploration quickly turns into a desperate struggle to escape its lingering curse.",
    "hints": ["doors", "silence", "figure", "kings", "students", "lament", "chapel", "footsteps", "eyes", "sounds"],
    "userSelection": [],
    "story": "The ancient chapel perched atop the hill, overlooking the Goan coastline. Local whispers told of three kings, poisoned and buried within its very walls. A group of brave students, armed with curiosity, ignored the warnings and arrived at dusk. The chapel’s heavy wooden doors creaked open, revealing a chilling silence inside. As night deepened, a cold draft swept through the nave, carrying faint sounds of struggle. Footsteps echoed from the altar, where no one stood. A shimmering figure appeared in the archway, its eyes filled with ancient sorrow. The air grew heavy, thick with the scent of old blood. Panic set in. They tried to leave, but the main door was now sealed. Trapped, they heard the desperate cries of betrayed monarchs, joining the chapel's eternal lament."
    },
    {
    "title": "The Deserted Village's Curse",
    "summary": "At the abandoned Kuldhara Village, once mysteriously deserted overnight, a curious historian seeks answers. As night falls, he confronts the chilling remnants of its past: ghostly whispers, unexplained phenomena, and the lingering presence of those who vanished, realizing the ancient curse still holds power. His quest for truth becomes a desperate struggle to escape the village's haunted embrace.",
    "hints": ["houses", "path", "dust", "voice", "historian", "silence", "shadows", "village", "moonlight", "curse"],
    "userSelection": [],
    "story": "The desolate Kuldhara Village lay still under the desert sun, a monument to a mysterious exodus. A lone historian, obsessed with its legend, arrived at dusk. He walked among the crumbling houses, the only sound the crunch of sand beneath his boots. An eerie silence hung heavy, unbroken by birds or insects. As moonlight bathed the narrow path, a faint whisper reached his ears, seemingly from nowhere. He dismissed it as the wind, but a chill ran down his spine. A fleeting shadow darted between the ruined walls. He called out, his voice swallowed by the emptiness. The air grew heavy, thick with unseen dread. He knew then; the village's curse was real. He turned to leave, but the dusty road behind him had vanished."
    },
]
return easyStories;
}

function getMediumStories(){
    let mediumStories = [
            {
        title: "The Spectral Ward's Grasp",
        summary: "In the chilling depths of an abandoned hospital, a new night guard's routine patrol takes a terrifying turn. Investigating strange, rhythmic noises, he stumbles upon a desolate isolation wing where unsettling markings on the walls and a single, ancient object hint at the facility's disturbing past. The lingering, malevolent presence of its former inhabitants slowly reveals itself, making his night shift an inescapable nightmare.",
        hints: ['shadow', 'spine', 'room', 'marks', 'doll', 'whisper', 'eyes', 'home', 'silence', 'chill', 'doors'],
        userSelection: [],
        story: "The relentless chill in the old hospital's abandoned wing wasn't just from the shattered windows; it was a pervasive dread. Liam, the new night guard, felt a prickle down his spine as he checked the heavily locked doors of the isolation ward, a sense of unseen eyes upon him. A faint, rhythmic scratching echoed from deep within Room 7. He hesitated, flashlight beam trembling, before pushing the heavy, rusted door open. The room was starkly bare, save for a single, rusted bed frame. On the dust-covered wall, hundreds of tiny, parallel marks marred the paint, forming an unsettling, intertwining pattern that seemed to writhe in the dim light. As his light swept across the grime-covered floor, he saw a single, antique doll, its porcelain eyes staring blankly at the wall, radiating an unsettling silence. Then, from the oppressive darkness behind him, a chilling whisper, 'We're still here, Liam... you are home now.'"
    },
    {
        title: "Echoes of the Blackwood Deep",
        summary: "A seemingly innocent camping trip in the foreboding Blackwood Forest spirals into a harrowing nightmare for three friends. Ignoring dire local warnings, they venture deep into the unsettling quiet of the woods. As darkness descends, unsettling noises and increasingly menacing, mysterious presences emerge from the depths, revealing the forest's ancient, terrifying secrets and turning their adventure into a desperate fight for survival against unseen entities.",
        hints: ['shadows', 'warnings', 'silence', 'whispers', 'chill', 'tents', 'tapping', 'giggle', 'darkness', 'eye', 'forest', 'leaves'],
        userSelection: [],
        story: "The roaring campfire crackled, casting dancing shadows among the towering pines, briefly warding off the encroaching gloom. Sarah, Mark, and Emily, full of youthful bravado, had foolishly ignored the old local's chilling warnings about the infamous Blackwood Forest. Deep within the woods, an unnerving silence fell upon them, far too profound for a natural wilderness. It was broken only by the rustling of dry leaves and what sounded distinctly like faint whispers carried on the unforgiving wind. Later, huddled desperately in their flimsy tents, a profound chill seeped into their sleeping bags, colder than any mere night air. A rhythmic tapping began, not on their tent, but eerily from within the surrounding trees. It grew louder, more insistent, accompanied by what sounded uncannily like a child's giggle – distorted, mocking, and far too close. Mark peered through the mesh, seeing nothing but the impenetrable darkness. Then, a single, malevolent, glowing eye opened in the black, staring back. They didn't scream; they simply froze, listening to the very forest breathing around them."
    },
    {
        title: "Phantom Passenger of Delhi Road",
        summary: "A late-night drive on a notoriously foggy Delhi road becomes a terrifying ordeal for Aryan. He encounters a mysterious woman in a white saree, who inexplicably appears in his back seat. As the temperature inside the car plummets and the scent of old flowers fills the air, a chilling ghostly voice requests a ride to a nearby cemetery, leaving Aryan with a haunting and unforgettable reminder of his spectral passenger and the thin veil between worlds.",
        hints: ['headlights', 'road', 'figure', 'woman', 'saree', 'seat', 'face', 'flowers', 'car', 'breath', 'voice', 'cemetery'],
        userSelection: [],
        story: "The piercing headlights cut through the dense, swirling fog on the desolate Delhi Cantt road, illuminating only a few feet ahead. Aryan, driving home late after a long shift, felt an inexplicable chill seep into the car despite the warm night, a premonition he couldn't shake. Ahead, a solitary, indistinct figure emerged from the swirling mist: a woman in a stark white saree, her back turned towards him, seemingly waiting. He slowed, wary, his instincts screaming at him. As he cautiously passed, she was suddenly and impossibly inside his back seat. Her long, disheveled black hair completely obscured her face, a void in the rearview mirror. A faint, cloying scent of old, withered flowers filled the car, making him gag. Aryan's hands gripped the steering wheel, knuckles white as bone, his heart hammering against his ribs. The temperature inside plummeted further, causing his breath to fog. A cold breath ghosted across his ear. 'Drop me at the cemetery,' a raspy, ancient voice whispered, barely audible but terrifyingly clear. He slammed the brakes, the car skidding, and looked back. The seat was utterly empty, but the faint, sickly sweet scent of jasmine lingered, a chilling, undeniable reminder of his spectral passenger."
    },
    {
        title: "The Manor of Whispers Unveiled",
        summary: "A group of daring explorers, fueled by an insatiable curiosity, embarks on a perilous venture into a notoriously haunted mansion. They defiantly disregard generations of chilling local legends detailing the cursed grounds and tragic past within its ancient walls. As they navigate the crumbling structure, they are confronted by an escalating series of terrifying supernatural phenomena, from disembodied whispers echoing through empty halls to unseen touches and malevolent presences, gradually realizing they are not alone within the mansion's eerie confines. Their brave exploration quickly transforms into a desperate, terrifying fight for survival against the dwelling's vengeful spectral inhabitants.",
        hints: ['mansion', 'legends', 'explorers', 'gates', 'flashlight', 'fragrance', 'breeze', 'giggle', 'hand', 'whispers', 'voices', 'phones', 'house'],
        userSelection: [],
        story: "The crumbling mansion stood silhouetted ominously against the stormy sky, a dark silhouette against the turbulent clouds. Local legends, passed down through generations, vividly warned against its cursed grounds and the restless spirits within. A group of young explorers, daring and foolish in their pursuit of thrills, crept past the rusty, dilapidated gates, their excitement tinged with a nervous anticipation. Inside, dust motes danced in the lone beam of a single flashlight, cutting through the oppressive gloom. A strange, sweet, almost cloying fragrance hung heavy in the stale air, like forgotten flowers left to decay. Suddenly, an unnaturally cold breeze swept through the empty, cavernous halls, extinguishing their light, plunging them into absolute darkness. A child's faint, chilling giggle echoed from deeper within the mansion, distorted and far too close. One of them, a girl named Maya, felt a tiny, icy hand brush her leg, causing her to freeze. Her heart pounded against her ribs like a trapped bird. Then, the whispers began, a sinister chorus of tiny voices swirling from the shadows, surrounding them. They fumbled frantically for their phones, but the screens remained stubbornly black, refusing to offer any light or connection to the outside world. They were truly not alone in this cursed house."
    },
    {
        title: "The Cursed Night of Bhangarh",
        summary: "Ancient legend strictly warns that no one should dare to remain within Bhangarh Fort after sunset, due to an ancient and potent curse that binds restless spirits to its desolate grounds. A curious tourist, fueled by skepticism and defiance, chooses to challenge this ominous warning by spending the entire night within the crumbling ruins. As darkness fully descends, he soon discovers the chilling and terrifying reality of the fort's spectral inhabitants, facing not just unseen presences but actively vengeful spirits that relentlessly roam its haunted grounds, turning his act of defiance into a perilous and desperate struggle for survival against an inescapable supernatural force.",
        hints: ['fort', 'tourist', 'legends', 'sunset', 'tower', 'night', 'breeze', 'melody', 'figure', 'eyes', 'whisper', 'walls', 'ruins'],
        userSelection: [],
        story: "The ancient fort of Bhangarh stood silent and imposing as dusk painted the sky in shades of bruised purple and ominous orange. Rahul, a lone tourist driven by a thirst for the macabre, scoffed openly at the local legends warning against staying within its crumbling confines after sunset. He defiantly climbed to the highest, most precarious tower, eager to witness the forbidden night descend upon the desolate landscape. A sudden, piercingly cold breeze swept through the empty chambers, carrying with it a faint, mournful melody that seemed to weave through the very stones. He dismissed it, convincing himself it was merely the wind playing tricks. Suddenly, a distinct, shadowy figure appeared in the archway below, its hollow eyes fixed unblinkingly on him, radiating an ancient malice. No sound escaped its lips, but a chilling whisper echoed directly in his mind: 'You've crossed the boundary, and now you pay.' Panic surged through his veins. He scrambled desperately down the crumbling walls, the fort's vengeful spirits seemingly pursuing him, their cold touch undeniable, through the desolate ruins. Bhangarh had claimed another soul for its eternal collection."
    },
    {
        title: "The Tide of Lost Souls at Dumas",
        summary: "A group of thrill-seeking friends, disregarding ominous local legends, visits the notorious black sands of Dumas Beach, a place infamous for unexplained disappearances. As night deepens and the moon remains hidden, they begin to hear chilling, disembodied whispers carried on the relentless wind, subtly drawing them deeper towards the desolate shore. They soon confront a terrifying and seemingly inescapable fate as a malevolent supernatural presence reveals its true, overwhelming power, transforming their search for adrenaline into a night of pure, unadulterated horror where the boundary between worlds blurs and the lost souls seek company.",
        hints: ['sands', 'friends', 'warnings', 'shore', 'waves', 'whispers', 'wind', 'laughter', 'names', 'dread', 'footprints', 'darkness', 'embrace'],
        userSelection: [],
        story: "The notorious black sands of Dumas Beach stretched endlessly under the oppressive, moonless sky, absorbing all light. Four friends, fueled by an insatiable hunger for thrill and defiance, disregarded the grim local warnings about the beach's dark history. They walked slowly along the desolate shore, the rhythmic crash of the powerful waves strangely muted, as if muffled by an unseen presence. Soon, faint, almost imperceptible whispers reached their ears, carried on the chilling, unseen wind that swirled around them. It sounded eerily like a chorus of distant, mocking laughter, both ethereal and strangely inviting, luring them further into the gloom. As they ventured deeper, the whispers grew clearer, seeming to call their individual names from all directions. A profound, bone-deep cold dread settled over them, paralyzing their movements. They looked back; their footprints in the black sand were visibly vanishing behind them, not eroded by the waves, but as if actively dragged under the surface by an unseen force. The oppressive darkness seemed to press in, thick and suffocating, swallowing every flicker of courage. A chilling, powerful force pulled relentlessly at their ankles, a silent, malevolent, unseen embrace dragging them towards an unknown fate. On the desolate shore, only the whispers remained, now a triumphant chorus."
    },
    {
        title: "The Haunting Reel of Mukesh Mills",
        summary: "A daring documentary crew, driven by a desire to expose long-held supernatural truths, ventures deep into Mumbai's infamous and abandoned Mukesh Mills. Known for its chilling history of unexplained deaths and eerie occurrences, the crew soon finds themselves inexplicably trapped within the crumbling, vast complex. They face the terrifying reality of its unseen, lingering residents and malevolent energies. Their investigative journey quickly transforms from a search for evidence into a desperate, pulse-pounding struggle for survival against the mill's vengeful and relentless ghostly inhabitants, as the boundary between the living and the dead blurs with each passing moment.",
        hints: ['mills', 'crew', 'gates', 'camera', 'silence', 'shadow', 'factory', 'air', 'whispers', 'figure', 'corridor', 'exit', 'ghosts'],
        userSelection: [],
        story: "The desolate Mukesh Mills stood stark against the sprawling Mumbai skyline, a decaying monument to forgotten industry and lingering tragedy. A documentary crew, bold and ambitious in their pursuit of paranormal phenomena, cautiously entered its crumbling gates, their professional camera poised and ready to capture the eerie atmosphere. Inside, an unnatural, almost suffocating silence enveloped them, broken only by the exaggerated crunch of debris underfoot with every step they took. Then, a fleeting, indistinct shadow darted across a distant, grimy window in the derelict factory, too quick to properly identify. The vast, cavernous air grew heavy, thick with the undeniable scent of damp concrete, forgotten oil, and an overwhelming, unseen dread. Faint, chilling whispers began to circulate, like a forgotten conversation from the tragic past of the mill workers. A tall, spectral figure appeared silently at the end of a long, dark corridor, its form shimmering eerily in the dim light, radiating malevolence. Panic set in, a visceral, overwhelming wave. They raced desperately for the nearest exit, but the massive, rusty doors slammed shut with a deafening clang, locking them inside with the vengeful ghosts of Mukesh Mills, their only escape now a terrifying uncertainty."
    },
    {
        title: "Shaniwarwada's Midnight Lament",
        summary: "At the historically significant and deeply haunted Shaniwarwada Fort in Pune, a new night watchman's routine shift abruptly transforms into a terrifying ordeal. As darkness consumes the ancient structure, he encounters the infamous, desperate cry of a brutally murdered young prince, a chilling sound that resonates through the very stone of the fort. This spectral lament draws him deeper into the fort's tragic and violent past, forcing him to confront not just the lingering presence of the prince, but other unseen entities, in a desperate struggle to maintain his sanity and find an escape from its cursed embrace.",
        hints: ['gate', 'watchman', 'walls', 'gloom', 'echo', 'courtyards', 'hallway', 'cry', 'voice', 'panic', 'figure', 'torch', 'darkness'],
        userSelection: [],
        story: "The massive, ominous iron gate of Shaniwarwada Fort groaned shut with a final, echoing clang, trapping Arjun, the new night watchman, irrevocably within its ancient, imposing walls. He began his solitary rounds, his trembling flashlight beam piercing the oppressive gloom that clung to every shadow. A cold, pervasive echo seemed to follow him relentlessly through the deserted courtyards, a phantom presence. As he approached the notorious hallway, infamous for its bloody history, a faint, desperate cry pierced the unnatural silence of the night: 'Kaka mala vachva!' (Uncle, save me!). It was the unmistakable, ghostly voice of a brutally murdered young prince, still agonizing for help. A wave of bone-chilling panic seized him, paralyzing his limbs. A shadowy, indistinct figure darted across the archway, just beyond the periphery of his sight, hinting at other restless spirits. He fumbled frantically, dropping his torch, plunging himself into utter darkness. The chilling voice grew louder, closer, an insidious whisper in his ear. He stumbled backward, desperate for an escape, but the fort's ancient, malevolent power seemed to hold him fast within its cold, unyielding stone walls, a prisoner of its tragic past."
    },
    {
        title: "Goa's Poisoned Crown: Three Kings Chapel",
        summary: "Perched atop a desolate Goan hill, the Three Kings Chapel conceals a dark and bloody history of monarchs poisoned by their own kin. A group of curious students, drawn by the chapel's macabre legends, bravely dares to explore its eerie interior after dusk, seeking supernatural encounters. They soon find themselves overwhelmed by chilling phenomena: disembodied sounds, unsettling spectral figures, and a pervasive sense of suffocating dread. They rapidly realize the chapel's tragic and violent past still echoes profoundly within its ancient, cursed walls, and their innocent exploration swiftly transforms into a desperate, terrifying struggle to escape its lingering and inescapable curse.",
        hints: ['chapel', 'hill', 'whispers', 'kings', 'students', 'curiosity', 'doors', 'silence', 'nave', 'sounds', 'figure', 'eyes', 'lament'],
        userSelection: [],
        story: "The ancient chapel, a silent sentinel, perched ominously atop the desolate Goan hill, overlooking the vast, dark coastline. Local whispers told grim tales of three ambitious kings, brutally poisoned by their own kin and buried within its very walls, their restless spirits bound. A group of brave students, armed with youthful curiosity and a thirst for the supernatural, ignored the dire warnings and arrived precisely at dusk. The chapel’s massive, heavy wooden doors groaned open with a chilling sound, revealing an oppressive, foreboding silence within. As night deepened, an unnaturally cold draft swept through the ancient nave, carrying faint, disembodied sounds of struggle and desperate gasps. Spectral footsteps echoed from the crumbling altar, where no one stood visible. A shimmering, translucent figure appeared silently in the archway, its hollow eyes filled with an ancient, profound sorrow and unresolved agony. The very air grew heavy, thick with the pervasive scent of old blood and lingering decay. Panic set in, a cold, visceral grip. They tried desperately to leave, but the main door was now inexplicably sealed shut. Trapped within, they heard the desperate cries of the betrayed monarchs, their ghostly lament joining the chapel's eternal, chilling chorus, a reminder of the curse."
    },
    {
        title: "Kuldhara's Eternal Exile",
        summary: "Deep within the desolate Thar Desert, the ghost village of Kuldhara stands as a chilling testament to a sudden, unexplained exodus centuries ago, its streets now forever empty. A determined paranormal investigator, drawn by the unsettling legends of a powerful ancient curse, ventures into its abandoned homes and desolate streets under the cover of a starless, moonless night. He soon finds himself confronting not just the eerie silence, but distinct ghostly whispers, terrifying spectral shadows, and inexplicable phenomena that defy all logic, forcing him to question the very fabric of reality as the village's potent, ancient curse tries to claim another living soul. His brave quest for answers quickly transforms into a desperate and terrifying fight for survival to escape its haunting, inescapable grasp before he too becomes a permanent, exiled resident of Kuldhara.",
        hints: ['desert', 'village', 'historian', 'legend', 'dusk', 'homes', 'path', 'moonlight', 'whisper', 'spine', 'shadow', 'voice', 'air', 'presence', 'curse', 'road', 'fate'],
        userSelection: [],
        story: "Deep within the desolate Thar Desert, the abandoned Kuldhara Village lay utterly still under the harsh, unblinking desert sun, a chilling monument to a mysterious exodus centuries ago when its entire population vanished overnight. Dr. Anya Sharma, a renowned paranormal historian obsessed with its haunting legend, arrived precisely at dusk, her audio recorder already active, hoping to capture some trace of the past. She walked slowly among the crumbling, empty houses, the only sound the crunch of fine sand beneath her boots. An eerie, profound silence hung heavy in the air, unbroken by birdsong or the buzz of insects, a silence that felt unnatural. As the last rays of sunlight faded and moonlight began to bathe the narrow path, a faint, disembodied whisper, like a forgotten secret, brushed her ear, seemingly from nowhere. She dismissed it as merely the wind, but a profound, icy chill ran down her spine. A fleeting shadow, too swift and dark to be natural, darted between the ruined walls, just beyond her peripheral vision. She called out, her voice swallowed by the overwhelming emptiness. The very air grew heavy, thick with an unseen, malevolent presence. Anya knew then, with a terrifying certainty; the village's ancient curse was terrifyingly real and actively sentient. She turned frantically to leave, but the dusty road behind her had inexplicably vanished, sealing her terrifying fate within Kuldhara's cursed boundaries, destined to join its eternal exile."
    }
    ]

    return mediumStories;
}


export {getEasyStories ,getMediumStories};